---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: checkout
      uses: actions/checkout@v2 # $GITHUB_WORKSPACE
  playbooks:
    name: Playbooks
    runs-on: self-hosted
    strategy:
      matrix:
        include:
          - playbook: .github/playbook.yml
