---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: checkout
      uses: actions/checkout@v2 # $GITHUB_WORKSPACE
    - name: Execute Ansible Playbook
      #uses: saubermacherag/ansible-playbook-docker-action@v1.3
      with:
        playbookName: .github/playbook.yml
        verbosity: vv
