on: [push]

jobs:
  hello_world_job:
    runs-on: self-hosted
    name: Say hello to javascript Action App
    steps:
    - name: checkout
      uses: actions/checkout@v2 # $GITHUB_WORKSPACE
    - name: javascript action step
      id: hello
      uses: ./
      with:
        who-to-greet: 'Priyaranjan Barik'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
